extends:
  - next
  - '@zakodium/eslint-config/typescript-react'
rules:
  '@typescript-eslint/no-explicit-any': off
  import/no-unresolved: off
  import/order:
    - warn
    - groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index']
      newlines-between: always
      alphabetize:
        order: asc
      pathGroups:
        - pattern: '{@/*,@/**}'
          group: external
          position: after
      pathGroupsExcludedImportTypes: ['builtin']
